# This file is used to manage the OpenHarmony project sig_group information
[[sig_group]]
name = "sig-ai-framework"
description = "负责AI框架相关模块的架构设计、评审、决策以及开发"
leader = { gitee_id = "https://gitee.com/zhanghaibo5", email = "zhanghaibo5@huawei.com" }
sub_system = ["L1S_AI"]

[[sig_group]]
name = "sig-ai_framework_integration"
description = "负责在OpenHarmony平台上提供三方AI推理框架的集成和维护"
leader = { gitee_id = "https://gitee.com/wang-huaxin", email = "wanghuaxin@kaihongdigi.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-api"
description = "负责制定OpenHarmony平台的API设计规范和API社区治理，对API变更进行设计与评审"
leader = { gitee_id = "https://gitee.com/huawei_qiangbo", email = "qiangbo2@huawei.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-appframework"
description = "负责应用程序框架(元能力、ArkUI、事件通知等)相关模块的架构设计、评审、决策及开发"
leader = { gitee_id = "https://gitee.com/huawei_qiangbo", email = "qiangbo2@huawei.com" }
sub_system = [
    "L1S_Global",
    "L1S_AppExecFwk",
    "L1S_AAFwk",
    "L1S_ArkUI",
    "L1S_Notification",
]

[[sig_group]]
name = "sig-architecture"
description = "负责OpenHarmony架构（包括子系统/部件/代码仓的增加，合并，拆分和删除）相关的设计评审，《架构设计原则》和《OpenHarmony 系统架构》修订"
leader = { gitee_id = "https://gitee.com/im-off-this-week", email = "rengelin@huawei.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-basicsoftwareservice"
description = "负责OpenHarmony基础软件服务相关模块的架构设计、评审、决策及开发"
leader = { gitee_id = "https://gitee.com/handyohos", email = "zhangxiaotian@huawei.com" }
sub_system = [
    "L1S_DistributedSchedule",
    "L1S_ResourceSchedule",
    "L1S_StartUp",
    "L1S_Update",
    "L1S_Account",
    "L1S_BarrierFree",
    "L1S_InputMgrFwk",
    "L1S_Timezone",
    "L1S_ThemeFramework",
    "L1S_UploadAndDownload",
]

[[sig_group]]
name = "sig-blockchain"
description = "提供OpenHarmony数据上链功能，深度定制可适配OpenHarmony的数据上链组件"
leader = { gitee_id = "https://gitee.com/shangxuan_hz", email = "shangxuan@hyperchain.cn" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-bluetooth"
description = "提供OpenHarmony蓝牙服务以及蓝牙协议栈，提升蓝牙兼容性"
leader = { gitee_id = "https://gitee.com/cheng_guohong", email = "guohong.cheng@huawei.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-buildsystem"
description = "负责编译构建模块架构设计、评审、决策及开发"
leader = { gitee_id = "https://gitee.com/chenmudan", email = "chenmudan@huawei.com" }
sub_system = ["L1S_BuildSystem"]

[[sig_group]]
name = "sig-cellular_device_mgr"
description = "负责基于OpenHarmony平台，进行入云组件、端管云组件、终端安全等基础能力组件和行业应用组件的架构设计、评审、决策及开发"
leader = { gitee_id = "https://gitee.com/pengz123", email = "pengzhao.sh@chinatelecom.cn" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-compileruntime"
description = "负责语言编译和运行时相关软件模块架构设计、评审、决策及开发"
leader = { gitee_id = "https://gitee.com/klooer", email = "xianyuqiang@huawei.com" }
sub_system = ["L1S_CCRuntime", "L1S_Utils"]

[[sig_group]]
name = "sig-compliance"
description = "制定OpenHarmony的开源合规治理的规则、规范、流程，负责开发合规工具，并提供合规服务能力"
leader = { gitee_id = "https://gitee.com/jalenchen", email = "xianyuqiang@huawei.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-crossplatformui"
description = "开发和维护跨平台适配核心，包括为 OpenHarmony 拓展UI范式，让Web应用和各类小程序应用适配OpenHarmony的能力"
leader = { gitee_id = "https://gitee.com/o2team", email = "o2labs@163.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-dengluyi"
description = "为OpenHarmony 环境嵌入一个通用标准的多账号管理模块，与手机登录易App通信互操作，实现新用户的自动注册，老用户的自动登录，自动修改密码等功能"
leader = { gitee_id = "https://gitee.com/youngp7", email = "3119005904@mail2.gdut.edu.cn" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-devboard"
description = "提供OpenHarmony芯片&开发板移植规划和规范，负责芯片&开发板移植的架构设计、预审及开发工作"
leader = { gitee_id = "https://gitee.com/liuyang198591", email = "liu_yang@hoperun.com" }
sub_system = ["L1S_DevBoard"]

[[sig_group]]
name = "sig-distributeddatamgr"
description = "负责OpenHarmony数据管理服务相关模块的架构设计、评审、决策及开发"
leader = { gitee_id = "https://gitee.com/gong-a-shi", email = "gongashi@huawei.com" }
sub_system = ["L1S_DistributedDataMgr_DFS"]

[[sig_group]]
name = "sig-distributedhardwaremgr"
description = "负责OpenHarmony MSDP、电源管理、传感器服务、分布式硬件、USB相关模块的架构设计、评审、决策及开发"
leader = { gitee_id = "https://gitee.com/hhh2", email = "pengfei.hou@huawei.com" }
sub_system = [
    "L1S_MSDP",
    "L1S_DistributedHardwareMgr",
    "L1S_PowerMgr",
    "L1S_Sensors",
    "L1S_USB",
]

[[sig_group]]
name = "sig-docs"
description = "负责OpenHarmony版本配套开发者文档的构建和发布的评审及开发"
leader = { gitee_id = "https://gitee.com/neeen", email = "neen.yang@huawei.com" }
sub_system = ["L1S_Docs"]

[[sig_group]]
name = "sig-driver"
description = "负责构建OpenHarmony的统一硬件驱动平台HDF的架构设计、评审、决策及开发"
leader = { gitee_id = "https://gitee.com/shidi_snow", email = "zhaowenhua@huawei.com" }
sub_system = ["L1S_Drivers"]

[[sig_group]]
name = "sig-edu_data_specification"
description = "建设基于OpenHarmony的教育专属操作系统，积极与教育南北生态合作伙伴、教育管理单位、高校、科研单位，完善OpenHarmony上的教育生态建设"
leader = { gitee_id = "https://gitee.com/yongjie2020", email = "yongjie.yan@huawei.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-graphics"
description = "负责构建OpenHarmony的图形和窗口相关的架构设计、评审、决策及开发"
leader = { gitee_id = "https://gitee.com/abbuu", email = "liyu37@huawei.com" }
sub_system = [
    "L1S_Graphic_AGPEngine",
    "L1S_Graphic_AGPComponent",
    "L1S_Graphic_AGPWindows",
    "L1S_MultiModalInput",
]

[[sig_group]]
name = "sig-hilog"
description = "负责日志系统HiLog架构设计、评审、决策及开发"
leader = { gitee_id = "https://gitee.com/v11985", email = "wangfeng@iscas.ac.cn" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-ide"
description = "负责构建OpenHarmony IDE功能模块和插件相关的架构设计、评审、决策及开发"
leader = { gitee_id = "https://gitee.com/xiaojian_ide", email = "xiaojian756@huawei.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-industrial_internet"
description = "负责构建围绕OpenHarmony构建工业专属操作系统和软硬件生态相关的架构设计、评审、决策及开发"
leader = { gitee_id = "https://gitee.com/halhuangbin", email = "huangbin@talkweb.com.cn" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-infrastructure"
description = "负责构建围绕OpenHarmony构建工业专属操作系统和软硬件生态相关的架构设计、评审、决策及开发"
leader = { gitee_id = "https://gitee.com/xzmu", email = "kelei@iscas.ac.cn" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-iot-sensing-network"
description = "负责构建围绕OpenHarmony构建在2B行业物联感知场景所必须的网络协议能力增强"
leader = { gitee_id = "https://gitee.com/yoursywxf", email = "xiaofei3@huawei.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-kernel"
description = "负责构建OpenHarmony的内核存储、内存、调度、安全等能力增强，多内核兼容架构设计、评审、决策及开发"
leader = { gitee_id = "https://gitee.com/easy-to-see", email = "salient.yijian@huawei.com" }
sub_system = ["L1S_Kernel"]

[[sig_group]]
name = "sig-knowlege"
description = "负责构建OpenHarmony场景化Demo，撰写详细的开发指导书和课程"
leader = { gitee_id = "https://gitee.com/zeeman_wang", email = "zeeman.wang@huawei.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-linkboy"
description = "负责围绕OpenHarmony系统的适配和移植linkboy图形化编程软件，推广OpenHarmony系统生态"
leader = { gitee_id = "https://gitee.com/linkboy_crux", email = "910360201@qq.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-media"
description = "负责构建OpenHarmony的媒体框架&服务相关的架构设计、评审、决策及开发"
leader = { gitee_id = "https://gitee.com/dumingliang_hw", email = "dumingliang@huawei.com" }
sub_system = ["L1S_MultiMedia"]

[[sig_group]]
name = "sig-miniblink"
description = "负责构建基于OpenHarmony轻量化web引擎"
leader = { gitee_id = "https://gitee.com/ampereufo", email = "ampereufo@qq.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-mips"
description = "使能OpenHarmony支撑MIPS架构与MIPS设备，提供MIPS的软件包和系统构建等指导，并维护对MIPS架构的支持"
leader = { gitee_id = "https://gitee.com/hongtao6573", email = "tao.hong@ingenic.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-napi_generator"
description = "基于OpenHarmony标准系统,推出一些提升开发效率的NAPI框架代码生成工具"
leader = { gitee_id = "https://gitee.com/zhaojunxia2020", email = "zhaojunxia@kaihong.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-openblock"
description = "负责围绕OpenHarmony系统的适配和移植Blockly图形化编程软件，推广OpenHarmony系统生态"
leader = { gitee_id = "https://gitee.com/duzc2", email = "duzc2@163.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-opengfxdriver"
description = "基于Mesa 3D以及DRM驱动，使能其在OpenHarmony平台运行开源的图形渲染"
leader = { gitee_id = "https://gitee.com/frank-huangran", email = "frank.huangran@huawei.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-print"
description = "使能OpenHarmony开发打印服务功能，拓展及完善OpenHarmony在行业智能终端及其他打印设备的基本能力"
leader = { gitee_id = "https://gitee.com/eric.li", email = "eric.li@urovo.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-python"
description = "使能Python在OpenHarmony上的应用开发"
leader = { gitee_id = "https://gitee.com/delphi-tang", email = "delphi_tang@dt4sw.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-qa"
description = "制定社区开发相关流程，组织sig组转正评审， 运营和审视社区开发、sig组运作，发现问题并推动相关团队优化改进"
leader = { gitee_id = "https://gitee.com/xhuazi", email = "xw.hua@huawei.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-qt"
description = "负责完成基于OpenHarmony的QT软件开发框架的移植及适配，将适配OpenHarmony平台的代码，回馈至QT上游社区"
leader = { gitee_id = "https://gitee.com/cwc1987", email = "caiwc@sinux.com.cn" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-release"
description = "负责制定OpenHarmony的发布计划和协调各SIG团队完成OpenHarmony社区版本的发布工作"
leader = { gitee_id = "https://gitee.com/davidwulanxi", email = "wuyonghui9@huawei.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-riscv"
description = "负责移植和维护RISC-V设备和RISC-V TEE在OpenHarmony上能运行"
leader = { gitee_id = "https://gitee.com/yu_jia_geng", email = "jiageng08@iscas.ac.cn" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-robotics"
description = "基于OpenHarmony设计可支持AGV、AMR、RGV等移动机器人的技术架构、应用层接口标准、通讯协议"
leader = { gitee_id = "https://gitee.com/sunmingang", email = "sunmingang@jd.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-secure_element"
description = "基于OpenHarmony提供统一的安全芯片管理框架，提供安全芯片相关规范，支持标准化的高安系统安全业务部署安全芯片"
leader = { gitee_id = "https://gitee.com/leapsecond", email = "ang.li@huawei.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-security"
description = "负责构建OpenHarmony的应用权限、应用签名、设备认证和密钥管理等的架构设计、评审、决策及开发"
leader = { gitee_id = "https://gitee.com/yongjie2020", email = "yongjie.yan@huawei.com" }
sub_system = ["L1S_Security", "L1S_BIOMETRICS"]

[[sig_group]]
name = "sig-softbus"
description = "负责构建OpenHarmony的应用权限、应用签名、设备认证和密钥管理等的架构设计、评审、决策及开发"
leader = { gitee_id = "https://gitee.com/maerlii", email = "maerli@huawei.com" }
sub_system = [
    "L1S_Communication",
    "L1S_Location",
    "L1S_Communication_HW",
    "L1S_Communication_NetMgr",
]

[[sig_group]]
name = "sig-systemapplications"
description = "定义并构建OpenHarmony的系统应用，负责申请、实施孵化项目，广泛收集社区开发者需求，以持续完善系统应用的特性"
leader = { gitee_id = "https://gitee.com/nicolaswang", email = "icolas.wangfeng@huawei.com" }
sub_system = ["L1S_Applications"]

[[sig_group]]
name = "sig-tee"
description = "负责构建OpenHarmony的TEE的架构设计、评审、决策及开发，制定TEE相关标准，建立统一的TEE生态"
leader = { gitee_id = "https://gitee.com/fugengsheng", email = "fugengsheng@huawei.com" }
sub_system = ["L1S_TEE"]

[[sig_group]]
name = "sig-telephony"
description = "负责构建OpenHarmony的SIM卡、搜网、蜂窝数据、蜂窝通话、短彩信等蜂窝移动网络基础通信的架构设计、评审、决策及开发"
leader = { gitee_id = "https://gitee.com/zhang-hai-feng", email = "zhanghaifeng11@huawei.com" }
sub_system = ["L1S_telepony"]

[[sig_group]]
name = "sig-test"
description = "负责构建OpenHarmony的测试系统、兼容测试框架的架构设计、评审、决策及开发"
leader = { gitee_id = "https://gitee.com/gaohanyi1982", email = "gaohanyi@huawei.com" }
sub_system = ["L1S_Test"]

[[sig_group]]
name = "sig-toolchains"
description = "为OpenHarmony开发和提供最新的社区开源工具，提升开发者开发效率"
leader = { gitee_id = "https://gitee.com/berolinux", email = "bernhard.rosenkraenzer.ext@huawei.com" }
sub_system = ["NONE"]

[[sig_group]]
name = "sig-temp"
description = "为OpenHarmony CI平台临时验证在IT平台创建SIG&代码仓库"
leader = { gitee_id = "https://gitee.com/landwind", email = "mamingshuai1@huawei.com" }
sub_system = ["NONE"]
